### ISSUE TITLE
Missing authorization Error in projects screen

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#1059]
**Describe the bug**
When not logged in, the projects page shows an error in debug logs that seems to indicate that a request missing authorization is being made.

**To Reproduce**
1. Fresh install, or never having logged in before
2. Go to Projects
3. See in the debug logs a failing request because of missing JWT.

**Expected behavior**
Requests that require authorization should be hidden behind check if the user is logged in and only performed if logged in.

**Additional context**
Logs:
`
WARN  Possible Unhandled Promise Rejection (id: 1):
INatApiError: {"status":"401","errors":[{"errorCode":"401","message":"JWT is missing or invalid"}]}
INatApiError: {"status":"401","errors":[{"errorCode":"401","message":"JWT is missing or invalid"}]}
    at construct (native)
    at Wrapper (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:19909:64)
    at construct (native)
    at _callSuper (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:181193:106)
    at INatApiError (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:181201:25)
    at ?anon_0_ (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:181229:35)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:1360:26)
    at _next (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:1379:29)
    at tryCallOne (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:26466:26)
    at _callTimer (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:26385:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:26415:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:26578:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:2929:46)
    at anonymous (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:2741:45)
    at __guard (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:2913:15)
    at flushedQueue (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:2740:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.inaturalist.iNaturalistMobile:2734:33)
 LOG  12:04:25 | INatApiError | ERROR : Error requesting https://stagingapi.inaturalist.org/v2/projects/41347/membership?fields=(icon%3A!t%2Cproject_type%3A!t%2Ctitle%3A!t) (status: 401): [object Object]
 LOG  12:04:25 | logging.js | WARN : reactQueryRetry, error: {"status":"401","errors":[{"errorCode":"401","message":"JWT is missing or invalid"}]}, failureCount: 2, options: 
{
  "queryKey": [
    "fetchMembership",
    41347
  ]
}
 WARN  [INatApiError: {"status":"401","errors":[{"errorCode":"401","message":"JWT is missing or invalid"}]}]
`

**Comment by albullington** [comment]
@angielt is this still happening? it's still assigned to you

**Comment by angielt** [comment]
closed because no longer happening app ver 0.42.0
