### ISSUE TITLE
ObsEdit target object not found test error

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#676]
Error while running test suite.

```
 FAIL  tests/integration/ObsEdit.test.js (6.989 s)
  ● ObsEdit › UUID in params › should render the observation in params after viewing other observation

    RealmError: Target object not found

      178 |       // as a previous observation; otherwise, realm will error out
      179 |       // also using modified for updating observations which were already saved locally
    > 180 |       realm?.create( "Observation", obsToSave, "modified" );
          |              ^
      181 |     } );
      182 |     return realm.objectForPrimaryKey( "Observation", obs.uuid );
      183 |   }

      at Realm.create (src/realmModels/Observation.js:180:14)
      at Function.write (src/realmModels/Observation.js:176:12)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7)
      at Function.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)
      at Function.apply [as saveLocalObservationForUpload] (src/realmModels/Observation.js:183:4)
      at Object.saveLocalObservationForUpload (tests/integration/ObsEdit.test.js:58:45)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7)
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)

```

**Comment by jtklein** [comment]
I don't see this on main.
