### ISSUE TITLE
ObsDetails test error: viewedUpdates not called

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#677]
Error while running test suite

```
FAIL  tests/integration/ObsDetails.test.js
  ● ObsDetails › with an observation where we don't know if the user has viewed comments › should make a request to observation/viewedUpdates

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      66 |         await screen.findByText( `@${mockObservation.user.login}` )
      67 |       ).toBeTruthy();
    > 68 |       expect( inatjs.observations.viewedUpdates ).toHaveBeenCalledTimes( 1 );
         |                                                   ^
      69 |       // Expect the observation in realm to have been updated with comments_viewed = true
      70 |       expect( observation.comments_viewed ).toBe( true );
      71 |     } );

      at Object.toHaveBeenCalledTimes (tests/integration/ObsDetails.test.js:68:51)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)

```

**Comment by jtklein** [comment]
I do not get this error on main. Maybe it is already fixed?
