### ISSUE TITLE
MyObservations signedInUsers test error

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#679]
Error when running test suite

```
 FAIL  tests/integration/MyObservations.test.js (7.019 s)
  ● MyObservations › when signed out › should not make a request to observations/updates

    expect(received).toEqual(expected) // deep equality

    Expected: 0
    Received: 1

      53 |       expect( apiMethod ).not.toHaveBeenCalled( );
      54 |       const signedInUsers = global.realm.objects( "User" ).filtered( "signedIn == true" );
    > 55 |       expect( signedInUsers.length ).toEqual( 0 );
         |                                      ^
      56 |       renderAppWithComponent( <MyObservationsContainer /> );
      57 |       const loginText = i18next.t( "Log-in-to-contribute-your-observations" );
      58 |       expect( await screen.findByText( loginText ) ).toBeTruthy( );

      at toEqual (tests/integration/MyObservations.test.js:55:38)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12
      at apply (tests/integration/MyObservations.test.js:51:42)
      at Object.testApiMethodNotCalled (tests/integration/MyObservations.test.js:69:13)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7)
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)
```

**Comment by jtklein** [comment]
I do not get this error on main.
