### ISSUE TITLE
ActivityHeader test error: not wrapped in act

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#680]
```
console.error
    Warning: An update to ActivityHeader inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at item (/Users/amanda/iNaturalistReactNative/src/components/ObsDetails/ActivityHeader.js:34:3)
        at View
        at Component (/Users/amanda/iNaturalistReactNative/node_modules/react-native/jest/mockComponent.js:28:18)
        at RCTScrollView
        at Component (/Users/amanda/iNaturalistReactNative/node_modules/react-native/jest/mockNativeComponent.js:17:18)
        at ScrollViewMock (/Users/amanda/iNaturalistReactNative/node_modules/react-native/jest/mockScrollView.js:22:23)
        at className (/Users/amanda/iNaturalistReactNative/node_modules/nativewind/dist/styled/index.js:23:23)
        at RCTSafeAreaView
        at Component (/Users/amanda/iNaturalistReactNative/node_modules/react-native/jest/mockNativeComponent.js:17:18)
        at className (/Users/amanda/iNaturalistReactNative/node_modules/nativewind/dist/styled/index.js:23:23)
        at className (/Users/amanda/iNaturalistReactNative/node_modules/nativewind/dist/styled/index.js:23:23)
        at component (/Users/amanda/iNaturalistReactNative/node_modules/nativewind/dist/styled-component.js:10:57)
        at children (/Users/amanda/iNaturalistReactNative/src/components/SharedComponents/ScrollViewWrapper.js:13:31)
        at ObsDetails (/Users/amanda/iNaturalistReactNative/src/components/ObsDetails/ObsDetails.js:68:34)
        at children (/Users/amanda/iNaturalistReactNative/src/components/App.js:39:17)
        at children (/Users/amanda/iNaturalistReactNative/src/providers/ObsEditProvider.js:41:29)
        at children (/Users/amanda/iNaturalistReactNative/node_modules/@react-navigation/core/src/EnsureSingleNavigator.tsx:20:49)
        at initialState (/Users/amanda/iNaturalistReactNative/node_modules/@react-navigation/core/src/BaseNavigationContainer.tsx:82:7)
        at value (/Users/amanda/iNaturalistReactNative/node_modules/@react-navigation/native/src/theming/ThemeProvider.tsx:11:41)
        at theme (/Users/amanda/iNaturalistReactNative/node_modules/@react-navigation/native/src/NavigationContainer.tsx:55:5)
        at children (/Users/amanda/iNaturalistReactNative/node_modules/@gorhom/bottom-sheet/mock.js:16:37)
        at apply (/Users/amanda/iNaturalistReactNative/node_modules/@callstack/react-theme-provider/src/createThemeProvider.js:14:3)
        at View
        at Component (/Users/amanda/iNaturalistReactNative/node_modules/react-native/jest/mockComponent.js:28:18)
        at PortalHost (/Users/amanda/iNaturalistReactNative/node_modules/react-native-paper/src/components/Portal/PortalHost.tsx:45:32)
        at children (/Users/amanda/iNaturalistReactNative/node_modules/react-native-safe-area-context/jest/mock.js:32:24)
        at children (/Users/amanda/iNaturalistReactNative/node_modules/react-native-paper/src/core/SafeAreaProviderCompat.tsx:38:50)
        at theme (/Users/amanda/iNaturalistReactNative/node_modules/react-native-paper/src/core/Provider.tsx:25:11)
        at children (/Users/amanda/iNaturalistReactNative/src/providers/INatPaperProvider.js:37:31)
        at QueryClientProvider (/Users/amanda/iNaturalistReactNative/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.js:52:22)

      48 |     const isActiveUserTheCurrentUser = async ( ) => {
      49 |       const current = await isCurrentUser( user?.login );
    > 50 |       setCurrentUser( current );
         |       ^
      51 |     };
      52 |     isActiveUserTheCurrentUser( );
      53 |

      at call (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:72:30)
      at printWarning (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:46:7)
      at error (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16677:9)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14877:5)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7510:7)
      at setCurrentUser (src/components/ObsDetails/ActivityHeader.js:50:7)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
```

**Comment by jtklein** [comment]
I don't see this on main.
